import{ManualResearchProvider,teamHref,tournamentMatches,headToHead}from'./data-layer.js';
const data=await(await fetch('/research.json')).json();const provider=new ManualResearchProvider(data);
const fixtureGames=[{id:'demo-live',home:'al-ittihad',away:'stade-malien',status:'LIVE',score:'78 — 72',date:'21 OCT / Q4 · 04:21'},{id:'demo-upcoming',home:'nabaya-sofas',away:'al-ittihad',status:'UPCOMING',score:'20:00',date:'22 OCT / 2026'}];
const put=(id,text)=>document.getElementById(id).textContent=text;
const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
function link(text,url){const a=el('a',text);a.href=url;return a;}
function sourceLinks(target,ids){const container=document.getElementById(target);container.append(el('span','المصادر: '));for(const id of ids){const s=data.sources[id];if(s?.url.startsWith('https://'))container.append(link(s.type.replaceAll('_',' '),s.url));}}
function logo(container,club){container.href=teamHref(club);container.setAttribute('aria-label',`صفحة ${club.arabicName}`);if(club.logo?.localReference&&/^assets\/[a-z-]+-reference\.png$/.test(club.logo.localReference)){const img=el('img');img.src='/'+club.logo.localReference;img.alt=club.arabicName+' — شعار مرجعي، غير معتمد للنشر';container.append(img);}else{container.append(el('span',club.officialName.split(' ').map(x=>x[0]).join('').slice(0,3)));container.classList.add('logo-fallback');}}
if(location.pathname.startsWith('/matches/')){document.getElementById('match-view').hidden=false;document.title='Al Ittihad vs Stade Malien | Road to BAL Tripoli 2027 — Preview';const h=headToHead('al-ittihad','stade-malien',provider.history('al-ittihad','stade-malien'));put('h2h-message',h.state==='NO_VERIFIED_MEETINGS_FOUND'?'لم نعثر على مواجهات سابقة موثقة بين الناديين.':'سجل المواجهات الموثقة');}
else{const slug=location.pathname.split('/')[2]||'al-ittihad';const club=provider.club(slug);if(!club){document.body.replaceChildren(el('h1','النادي غير موجود في المعاينة'));}else{document.getElementById('team-view').hidden=false;document.title=`${club.officialName} | Road to BAL Tripoli 2027 — Preview`;put('club-name',club.officialName.toUpperCase());put('club-arabic',club.arabicName);put('club-country',`${club.flag} ${club.country.toUpperCase()}`);put('club-group',`GROUP ${club.group}`);put('club-bio',club.shortBio);put('club-about',club.about||club.shortBio);logo(document.getElementById('club-logo'),club);const facts=document.getElementById('club-facts');if(club.city)facts.append(el('span',club.city.toUpperCase()));if(club.foundedYear)facts.append(el('span',`EST. ${club.foundedYear}${club.foundedScope==='MULTISPORT_CLUB'?' / النادي متعدد الرياضات':''}`));sourceLinks('bio-sources',club.bioSources);const honours=club.honours.filter(h=>h.verificationStatus==='VERIFIED');document.getElementById('honours').hidden=!honours.length;for(const h of honours){const row=el('div',undefined,'honour');row.append(el('strong',h.value));const copy=el('div');copy.append(el('h3',h.label),el('p',h.arabicLabel));if(h.asOf)copy.append(el('small','موثق حتى '+h.asOf));for(const id of h.sources)copy.append(link(' المصدر ↗',data.sources[id].url));row.append(copy);document.getElementById('honour-list').append(row);}if(club.id!=='al-ittihad')document.querySelector('.club-photo').hidden=true;
const games=tournamentMatches(club.id,fixtureGames);const list=document.getElementById('match-list');if(!games.length)list.append(el('p','لم يُعلن جدول مباريات هذا النادي في بيانات المعاينة.'));for(const game of games){const opponent=data.clubs.find(c=>c.id===(game.home===club.id?game.away:game.home));const row=el('article',undefined,'fixture-row');const opponentEl=el('div',undefined,'fixture-opponent');const mark=link(opponent.officialName.split(' ').map(x=>x[0]).join('').slice(0,3),teamHref(opponent));mark.className='logo-fallback';const copy=el('div');const name=link(opponent.officialName,teamHref(opponent));name.className='name';copy.append(name,el('div',`GROUP ${club.group} / ${opponent.country}`,'fixture-context'));opponentEl.append(mark,copy);const info=el('div');info.append(el('span',game.status+' / DEMO','fixture-state '+(game.status==='LIVE'?'live-demo':'')),el('strong',game.score,'fixture-score'),el('div',game.date,'fixture-context'));const open=link('مركز المباراة ↗','/matches/'+game.id);open.className='fixture-open';row.append(opponentEl,info,open);list.append(row);}}}

if(location.pathname==='/matches/demo-upcoming'){const game=fixtureGames.find(g=>g.id==='demo-upcoming');const clubs=[game.home,game.away].map(id=>data.clubs.find(c=>c.id===id));document.title=clubs.map(c=>c.officialName).join(' vs ')+' — Preview';document.querySelector('.live-clock').replaceChildren(el('span','UPCOMING / DEMO','micro'),el('strong','22 OCT · 20:00'));document.querySelector('.quarters').hidden=true;document.querySelector('.score-divider').hidden=true;document.querySelector('.leader').hidden=true;for(const [i,club]of clubs.entries()){const panel=document.querySelectorAll('.scores .team')[i];const mark=panel.querySelector('.identity-mark');mark.replaceChildren();mark.classList.remove('logo-fallback');logo(mark,club);for(const a of panel.querySelectorAll('h2 a,.arabic')){a.href=teamHref(club);a.textContent=a.classList.contains('arabic')?club.arabicName:club.officialName.toUpperCase();}panel.querySelector('.country').textContent=club.country.toUpperCase();panel.querySelector('strong').hidden=true;for(const selector of ['.broadcast-teams','.meeting-identity']){const a=document.querySelector(selector).querySelectorAll('a')[i];a.href=teamHref(club);a.textContent=club.officialName.toUpperCase();}}document.querySelector('.broadcast-status').textContent='22 OCT · 20:00 / DEMO · البث غير متاح حاليًا';document.querySelector('.h2h-example').hidden=true;document.querySelector('.detail-ending').hidden=true;put('h2h-message','لم يُستكمل البحث عن مواجهات هذا الزوج من الأندية بعد.');document.querySelector('.research-note').textContent='لا تُعرض نتائج تاريخية دون توثيق مستقل.';}
