import{z}from'zod';
const text=z.string().max(2000).refine(v=>!/[<>]/.test(v),'Plain text only');
const https=z.url().refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;},'HTTPS URL without credentials required');
export const sourceSchema=z.object({id:z.string().min(1),url:https,type:z.enum(['CLUB_OFFICIAL','FIBA','BAL','LOCAL_FEDERATION','LOCAL_LEAGUE','SPORTS_PRESS']),verificationStatus:z.enum(['VERIFIED','NEEDS_REVIEW','REJECTED']),checkedAt:z.iso.date(),reviewedBy:z.string().optional()});
const evidence=z.array(sourceSchema).min(1);
export const honourSchema=z.object({value:text,label:text,season:text.optional(),asOf:z.iso.date().optional(),verificationStatus:z.enum(['VERIFIED','NEEDS_REVIEW']),sources:evidence});
export const clubHistorySchema=z.object({clubId:z.string().min(1),category:z.literal('MEN'),city:text.optional(),foundedYear:z.number().int().min(1800).max(2100).optional(),foundedScope:z.enum(['MULTISPORT_CLUB','BASKETBALL_SECTION']).optional(),shortBio:text,honours:z.array(honourSchema),sources:evidence,verificationStatus:z.enum(['VERIFIED','NEEDS_REVIEW'])});
export const historicalMeetingSchema=z.object({id:z.string().min(1),category:z.literal('MEN'),home:z.string().min(1),away:z.string().min(1),date:z.iso.date(),competition:text,homeScore:z.number().int().min(0).max(999).nullable(),awayScore:z.number().int().min(0).max(999).nullable(),status:z.enum(['FINAL','CANCELLED','UNRESOLVED']),verificationStatus:z.enum(['VERIFIED','NEEDS_REVIEW']),sources:evidence}).superRefine((m,c)=>{if(m.home===m.away)c.addIssue({code:'custom',message:'Distinct canonical club identities required'});if(m.status==='FINAL'&&(m.homeScore===null||m.awayScore===null||m.homeScore===m.awayScore))c.addIssue({code:'custom',message:'Final basketball score must be decisive'});});
export const broadcastSchema=z.object({gameId:z.string().min(1),broadcastPlatform:text.nullable(),broadcastUrl:https.nullable(),broadcastEmbedId:z.string().max(200).regex(/^[a-zA-Z0-9_-]+$/).nullable(),broadcastStatus:z.enum(['NOT_AVAILABLE','SCHEDULED','LIVE','ENDED']),broadcasterName:text.nullable(),verificationStatus:z.enum(['VERIFIED','NEEDS_REVIEW']),sources:z.array(sourceSchema)}).superRefine((b,c)=>{if((b.broadcastUrl||b.broadcastEmbedId)&&(!b.broadcastPlatform||b.verificationStatus!=='VERIFIED'||!b.sources.length))c.addIssue({code:'custom',message:'Media requires provider and verified source evidence'});});
