import{chromium}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs';import{routes,activeRoute}from'./navigation-model.js';
const browser=await chromium.launch();const errors=[];let checks=0;const base='http://127.0.0.1:3032';const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(r.url()+':'+r.status())});async function ready(url){await page.goto(base+url);await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth));}
await ready('/');await page.screenshot({path:'verification/navigation-prototype/home-desktop-top.png'});assert.equal(await page.locator('.tournament-nav [aria-current=page]').getAttribute('href'),'/');checks++;await page.evaluate(()=>scrollTo(0,380));await page.waitForFunction(()=>document.querySelector('.tournament-header').classList.contains('is-scrolled'));assert.ok(await page.locator('.nav-level').boundingBox().then(b=>b.y>=0&&b.y<5));await page.screenshot({path:'verification/navigation-prototype/home-desktop-sticky.png'});checks++;
await page.setViewportSize({width:390,height:844});await ready('/');await page.screenshot({path:'verification/navigation-prototype/home-mobile-closed.png'});await page.getByRole('button',{name:'فتح قائمة البطولة'}).click();assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden');await page.screenshot({path:'verification/navigation-prototype/home-mobile-menu.png'});await page.locator('.menu-close').press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.closest('dialog')?.id),'tournament-menu');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.getElementById('tournament-menu').open&&document.querySelector('.menu-trigger').getAttribute('aria-expanded')==='false');assert.equal(await page.locator('#tournament-menu').isVisible(),false);assert.equal(await page.locator('.menu-trigger').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>document.activeElement.className),'menu-trigger');checks+=4;
for(const[url,file,section]of[['/teams/al-ittihad','team-desktop','/teams'],['/matches/demo-live','match-desktop','/matches']]){await page.setViewportSize({width:1440,height:900});await ready(url);assert.equal(await page.locator('.tournament-nav [aria-current=page]').getAttribute('href'),section);await page.screenshot({path:'verification/navigation-prototype/'+file+'.png'});assert.equal(await page.locator('a a').count(),0);checks+=2;}
for(const width of[360,390,412,768,1024,1440])for(const url of['/','/teams/al-ittihad','/matches/demo-live']){await page.setViewportSize({width,height:844});await ready(url);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,url+' '+width);checks++;}
for(const[p]of routes){assert.equal(activeRoute(p),p);const response=await page.request.get(base+p);assert.equal(response.status(),200,p);checks++;}assert.equal(activeRoute('/teams/stade-malien'),'/teams');assert.equal(activeRoute('/matches/123'),'/matches');checks+=2;
await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await ready('/teams/stade-malien');assert.equal(await page.locator('#club-logo img').count(),1);assert.equal(await page.locator('#club-logo').getAttribute('href'),'/teams/stade-malien');assert.equal(await page.locator('#club-logo img').getAttribute('src'),'/images/clubs/stade-malien.png');checks+=3;
assert.equal(errors.length,0,errors.join('\n'));await browser.close();fs.writeFileSync('verification/navigation-prototype/TEST_RESULTS.json',JSON.stringify({checks,passed:checks,consoleErrors:errors,date:'2026-10-06',widths:[360,390,412,768,1024,1440]},null,2));console.log(checks+' checks PASS; no missing images or console errors');
