import { z } from 'zod';
import seed from './club-data/profiles.json';
export const verificationSchema=z.enum(['VERIFIED','PARTIALLY_VERIFIED','NEEDS_REVIEW']);
const text=z.string().max(8000);
const sourceId=z.array(z.string()).min(1);
const evidence={sources:sourceId,verificationStatus:verificationSchema};
const honour=z.object({title:text,count:z.number().int().positive().optional(),year:z.number().int().min(1800).max(2100).optional(),note:text.optional(),verified:z.boolean(),...evidence});
export const clubProfileSchema=z.object({id:z.string(),slug:z.string(),aliases:z.array(z.string()),officialTournamentName:text,displayName:text,arabicName:text,shortName:text,country:text,countryCode:z.string().length(2),group:z.enum(['A','B']),city:text.optional(),foundedYear:z.number().int().min(1800).max(2100).optional(),foundedScope:text.optional(),league:text.optional(),arena:z.object({name:text,capacity:z.number().int().positive().optional()}).optional(),nickname:text.optional(),bioShort:text,bioLong:text,history:text,storyHeadline:text,domesticHonours:z.array(honour),continentalHonours:z.array(honour),continentalJourney:z.array(z.object({competition:text,year:z.number().int(),season:z.number().int().optional(),achievement:text,note:text.optional(),...evidence})),recentAchievements:z.array(z.object({year:z.number().int(),title:text,description:text,...evidence})),keyFacts:z.array(z.object({text,...evidence})),sources:z.array(z.object({id:z.string(),title:text,url:z.string().url().refine(s=>/^https:\/\//.test(s),'HTTPS sources required'),sourceType:z.enum(['FIBA','FEDERATION','CLUB','MEDIA']),verificationStatus:verificationSchema,checkedAt:z.string()})),fieldSources:z.record(z.string(),sourceId),verificationStatus:verificationSchema,verificationNotes:z.array(text),reviewItems:z.array(z.object({field:text,value:z.unknown(),sources:z.array(z.string()),verificationStatus:verificationSchema})),checkedAt:z.string()}).superRefine((p,ctx)=>{const ids=new Set(p.sources.map(s=>s.id));const refs=[...Object.values(p.fieldSources),...p.domesticHonours.map(x=>x.sources),...p.continentalHonours.map(x=>x.sources),...p.continentalJourney.map(x=>x.sources),...p.recentAchievements.map(x=>x.sources),...p.keyFacts.map(x=>x.sources),...p.reviewItems.map(x=>x.sources)];if(refs.flat().some(id=>!ids.has(id)))ctx.addIssue({code:'custom',message:'Unknown source reference'});for(const key of ['bioShort','bioLong','history','city','foundedYear','league','arena','nickname'])if(p[key as keyof typeof p]&&!p.fieldSources[key])ctx.addIssue({code:'custom',message:`Missing evidence for ${key}`})});
export type ClubProfile=z.infer<typeof clubProfileSchema>;
export const clubProfiles=seed.profiles.map(p=>clubProfileSchema.parse(p));
/** Publishing is per claim; aggregate club status never verifies an individual fact. */
export function publicClubProfile(profile:ClubProfile){const p=structuredClone(profile);const supported=(ids:string[])=>ids.length>0&&ids.every(id=>p.sources.some(s=>s.id===id&&s.verificationStatus==='VERIFIED'));for(const key of ['bioShort','bioLong','history','city','foundedYear','league','arena','nickname'] as const){if(p[key]&&!supported(p.fieldSources[key]||[])){if(key==='bioShort'||key==='bioLong'||key==='history')p[key]='';else delete p[key]}}
p.domesticHonours=p.domesticHonours.filter(h=>h.verified&&h.verificationStatus==='VERIFIED'&&supported(h.sources));p.continentalHonours=p.continentalHonours.filter(h=>h.verified&&h.verificationStatus==='VERIFIED'&&supported(h.sources));p.continentalJourney=p.continentalJourney.filter(h=>h.verificationStatus==='VERIFIED'&&supported(h.sources));p.recentAchievements=p.recentAchievements.filter(h=>h.verificationStatus==='VERIFIED'&&supported(h.sources));p.keyFacts=p.keyFacts.filter(h=>h.verificationStatus==='VERIFIED'&&supported(h.sources));p.reviewItems=[];p.verificationNotes=[];return p}
