import{readFileSync,writeFileSync}from'node:fs';
const edit=(p,f)=>writeFileSync(p,f(readFileSync(p,'utf8')));
edit('README.md',s=>s.replace('Uploads require admin authentication and validate extension, MIME, signature and 5 MB size. Only PNG/JPEG/WebP are served','Uploads require admin authentication and fully decode validated PNG/JPEG/WebP inputs, enforce 5 MB/16 MP limits, reject traversal names and animation, resize to at most 1600px, strip metadata and re-encode canonical WebP. Raster images are served').replace('Teams with spelling discrepancies are marked unverified in admin.','NB Staoueli remains flagged for spelling review; Stade Malien is confirmed by the French FIBA announcement.').replace('Proxy/IP-aware limiting, MFA, dedicated roles, backup encryption and CSP nonce hardening are deployment work, not claimed implemented.','Optional proxy-aware login limiting is implemented but must only be enabled behind a trusted proxy that replaces X-Real-IP and prevents direct origin access. MFA, dedicated roles, backup encryption and CSP nonce hardening are not claimed implemented.').replace('Two team spellings','One team spelling')+`

## Phase 2 operations and evidence

The working SQLite/SSE/ManualProvider architecture is retained. The canonical journey route is /the-road; /road remains available. Road states derive from actual games and confirmed qualification, with later stages locked. Match center has a dedicated scoreboard; mobile standings hides auxiliary columns while keeping record/difference/points legible. Fonts are locally bundled Noto Sans Arabic and Bebas Neue (SIL OFL; see assets/ licenses). Court graphics are original CSS geometry; no unlicensed tournament imagery is shipped.

Live control uses optimistic versions, a busy lock and per-command UUID receipts retained for 24 hours. Replaying the same authenticated command does not score twice; competing different commands with the same version return 409 and trigger a fresh snapshot. Undo reverses the latest score/clock change within the current status; changing status clears undo. Finished games cannot be reopened by ordinary controls. Use the explicit documented correction dialog, edit the game snapshot, supply an 8–400 character reason and confirm. Team IDs/date/group remain immutable; period totals must equal the scoreboard, final games need Q4+, clock zero and a winner. Correction resets the undo stack, recomputes standings and emits a correction announcement; the audit retains before/after and reason.

SSE sends an initial current revision on every connection, IDs, a 2-second retry directive and observable heartbeats. IDs are snapshot notifications, not a play-by-play replay log: reconnect always refreshes the latest authoritative data. Client refreshes are serialized and revisions cannot regress. A 10-second watchdog and browser offline state remove the LIVE label, freeze the displayed clock and show last reception time. Operator inactivity also retains the conservative 45-second delayed-data warning. The offline shell never presents cached scores as live.

For HTTPS hosting set SITE_URL to the exact public origin. It is used for canonical/share metadata, mutation Origin checks and Secure cookies behind the proxy. Enable TRUST_PROXY_IP=1 only after the proxy strips/replaces X-Real-IP and direct origin access is blocked. Missing/invalid client IP then fails closed. Local mode retains a global ten-attempt/15-minute login bucket; this can lock all login attempts and is unsuitable as the sole public proxy configuration.

## Backup and restore

Run npm run db:backup against the intended DATABASE_PATH. The native SQLite online backup API creates a consistent snapshot including WAL state, verifies integrity and foreign keys, and copies immutable media into a unique backup directory. Do not copy the live .db file alone. Treat backups as private because they contain password hashes, sessions and audit history. Use an encrypted off-host destination and a retention policy in hosting.

To restore, stop the server and every writer. Preserve the current data directory under a separate recovery name. Restore road.db and media from the same snapshot into a new empty directory, set DATABASE_PATH to it, provision/rotate the private admin password to revoke old sessions, run integrity/foreign-key checks, then start and smoke-test the server. Do not reuse old WAL/SHM files. The local QA exercises snapshot integrity and server restart persistence; a drill on the actual production host and storage remains required.

Run node scripts/phase2-verify.mjs after npm run build for isolated browser regressions, 20-client SSE/write/restart/offline checks, six-size visual captures, synthetic mobile performance and backup verification. It generates a private random test password, never provisions the public database, and stops its port 3001 test server. Baseline and final evidence are in verification/phase2/. Never run mutation tests against the event database.
`);
edit('DATA_SOURCES.md',s=>s.replace('Keep admin verification flags false for these spellings.','The Phase 2 French announcement confirms Stade Malien; NB Staoueli remains flagged.').replace('| Two team spellings | UNCONFIRMED | Admin editable and flagged |','| NB Staoueli / Nadi Staouedi spelling | UNCONFIRMED | Admin editable and flagged |')+`

## Phase 2 recheck

On 5 October 2026 the official indexed announcement was rechecked at https://about.fiba.basketball/en/news/introducing-the-road-to-bal-2027 and the French event article https://www.fiba.basketball/fr/events/fiba-africa-champions-clubs-road-to-bal-2027/news/introducing-the-road-to-bal-2027 . They confirm Tripoli 21–25 October, Groups A/B and top two to West Elite 16. The French article explicitly spells Stade Malien; its existing local verification flag was updated with a source-review audit entry. The Arabic/English display name and stable ID are retained. The Algeria spelling remains unresolved.

The announcement names Abidjan for West Elite 16, 10–15 November, but does not establish individual game dates/times or a complete competition classification contract. No new official game IDs, fixture times or rosters were verified. No fixtures/players/scores/statistics were added to the public seed. All visual/lifecycle test data lives in a separate QA database and is not tournament news. Direct event overview/games retrieval failed through the web tool; that is an access limitation, not evidence that FIBA is offline. No new scraping or undocumented API integration was added.
`);
